version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks: 
      - node-network
    depends_on:
      - "db"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - "nodeserver"
    networks: 
      - node-network
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks:
  node-network:
      driver: bridge


